// IPC Channel Constants — single source of truth for main ↔ renderer communication

// Request/Response (ipcMain.handle ↔ ipcRenderer.invoke)
export const IPC = {
  APP_BOOT_STATE_GET: 'app:boot-state-get',
  APP_FILE_FLUSH_RESULT: 'app:file-flush-result',
  APP_QUIT: 'app:quit',
  APP_RELAUNCH: 'app:relaunch',
  UPDATE_STATE_GET: 'update:state-get',
  UPDATE_CHECK: 'update:check',
  UPDATE_INSTALL: 'update:install',
  PANE_LIST: 'pane:list',
  PANE_ACTIVITY_SNAPSHOT_GET: 'pane:activity-snapshot-get',
  PANE_CREATE: 'pane:create',
  PANE_CLOSE: 'pane:close',
  PANE_MERGE: 'pane:merge',
  PANE_RENAME: 'pane:rename',
  PANE_RESUME_FULLSCREEN: 'pane:resume-fullscreen',
  PANE_JUMP: 'pane:jump',
  PANE_SEND_KEYS: 'pane:send-keys',
  PANE_GET_CONTENT: 'pane:get-content',
  PANE_CREATE_WORKTREE: 'pane:create-worktree',
  PANE_ATTACH_WORKTREE: 'pane:attach-worktree',
  PANE_DUPLICATE: 'pane:duplicate',
  PANE_START_REVIEW: 'pane:start-review',
  PANE_SEND_FIX: 'pane:send-fix',
  PANE_SESSION_LIST: 'pane:session-list',
  PANE_DUEL_CREATE: 'pane:duel-create',
  PANE_DUEL_RESOLVE: 'pane:duel-resolve',
  ACTION_CALLBACK: 'action:callback',
  TERMINAL_ATTACH: 'terminal:attach',
  TERMINAL_DETACH: 'terminal:detach',
  TERMINAL_RESIZE: 'terminal:resize',
  TERMINAL_SELECTION_EXPAND: 'terminal:selection-expand',
  TERMINAL_SCROLL: 'terminal:scroll',
  TERMINAL_WRITE: 'terminal:write',
  TERMINAL_UNLOCK_STDIN: 'terminal:unlock-stdin',
  PROJECT_LIST: 'project:list',
  PROJECT_SWITCH: 'project:switch',
  SETTINGS_DEFINITIONS: 'settings:definitions',
  SETTINGS_GET: 'settings:get',
  SETTINGS_UPDATE: 'settings:update',
  GIT_DIFF: 'git:diff',
  GIT_FILE_DIFF: 'git:file-diff',
  GIT_STATUS: 'git:status',
  GIT_BRANCHES: 'git:branches',
  AGENT_LIST: 'agent:list',
  AGENT_REFRESH: 'agent:refresh',
  AGENT_DEFAULTS_GET: 'agent:defaults-get',
  SYSTEM_APP_INFO: 'system:app-info',
  SYSTEM_CHECK: 'system:check',
  SESSION_INFO: 'session:info',
  ELECTRON_SETTINGS_GET: 'electron-settings:get',
  ELECTRON_SETTINGS_UPDATE: 'electron-settings:update',
  ELECTRON_SETTINGS_RESET: 'electron-settings:reset',
  AGENT_SESSION_GET: 'agent-session:get',
  AGENT_SESSION_SEARCH: 'agent-session:search',
  TOPICS_LIST: 'topics:list',
  WORKSPACE_HISTORY_LIST: 'workspace:history-list',
  WORKSPACE_HISTORY_TOUCH: 'workspace:history-touch',
  WORKSPACE_HISTORY_REMOVE: 'workspace:history-remove',
  WORKSPACE_OPEN_FOLDER: 'workspace:open-folder',
  WORKSPACE_NEW_PROJECT: 'workspace:new-project',
  WORKSPACE_CREATE_SESSION: 'workspace:create-session',
  WORKTREE_ORPHAN_INSPECT: 'worktree:orphan-inspect',
  WORKTREE_ORPHANS_LIST: 'worktree:orphans-list',
  WORKTREE_REMOVE: 'worktree:remove',
  WORKTREE_REOPEN: 'worktree:reopen',

  // LLM provider health
  LLM_STATUS: 'llm:status',
  AGENT_HEALTH: 'agent:health',

  // Kanban
  KANBAN_GET: 'kanban:get',
  KANBAN_BACKLOG_ADD: 'kanban:backlog-add',
  KANBAN_BACKLOG_REMOVE: 'kanban:backlog-remove',
  KANBAN_BACKLOG_UPDATE: 'kanban:backlog-update',
  KANBAN_BACKLOG_REORDER: 'kanban:backlog-reorder',
  KANBAN_DONE_ADD: 'kanban:done-add',
  KANBAN_DONE_CLEAR: 'kanban:done-clear',
  KANBAN_BATCH_LAUNCH: 'kanban:batch-launch',

  // System utilities
  SYSTEM_REVEAL_PATH: 'system:reveal-path',
  SYSTEM_OPEN_EXTERNAL: 'system:open-external',
  SYSTEM_OPEN_IN_EDITOR: 'system:open-in-editor',
  SYSTEM_LIST_EDITORS: 'system:list-editors',
  SYSTEM_PREVIEW_SUPPORT_BUNDLE: 'system:preview-support-bundle',
  SYSTEM_EXPORT_SUPPORT_BUNDLE: 'system:export-support-bundle',
  SYSTEM_CLIPBOARD_WRITE: 'system:clipboard-write',
  SYSTEM_CLIPBOARD_READ: 'system:clipboard-read',
  RENDERER_LOG: 'renderer:log',

  // Decompose
  DECOMPOSE_GENERATE: 'decompose:generate',

  // Recaps
  RECAP_GENERATE: 'recap:generate',

  // Pane Summary
  PANE_SUMMARY_LOAD_ALL: 'pane-summary:load-all',
  PANE_SUMMARY_REFRESH_ONE: 'pane-summary:refresh-one',
  PANE_SUMMARY_REFRESH_MANY: 'pane-summary:refresh-many',
  PANE_SUMMARY_GENERATE_RECAP_ONE: 'pane-summary:generate-recap-one',
  PANE_SUMMARY_GENERATE_RECAP_MANY: 'pane-summary:generate-recap-many',
  PANE_SUMMARY_REMOVE: 'pane-summary:remove',

  // Project file search
  PROJECT_FILE_SEARCH: 'project:file-search',
  PROJECT_TEXT_SEARCH: 'project:text-search',

  // File browser
  FILE_LIST: 'file:list',
  FILE_READ: 'file:read',
  FILE_READ_BINARY: 'file:read-binary',
  FILE_CREATE: 'file:create',
  FILE_CREATE_DIR: 'file:create-dir',
  FILE_WRITE: 'file:write',
  FILE_FORMAT: 'file:format',
  FILE_FORMAT_CANCEL: 'file:format-cancel',
  LSP_ACQUIRE: 'lsp:acquire',
  LSP_RELEASE: 'lsp:release',
  LSP_SEND: 'lsp:send',
  FILE_DELETE: 'file:delete',
  FILE_RENAME: 'file:rename',
  FILE_COPY: 'file:copy',
  FILE_MOVE: 'file:move',
  FILE_WATCH_ROOT: 'file:watch-root',

  // Marketplace
  MARKETPLACE_SOURCES_LIST: 'marketplace:sources-list',
  MARKETPLACE_SOURCE_ADD: 'marketplace:source-add',
  MARKETPLACE_SOURCE_REMOVE: 'marketplace:source-remove',
  MARKETPLACE_SOURCE_UPDATE: 'marketplace:source-update',
  MARKETPLACE_BROWSE: 'marketplace:browse',
  MARKETPLACE_PREVIEW: 'marketplace:preview',
  MARKETPLACE_INSTALL: 'marketplace:install',
  MARKETPLACE_UNINSTALL: 'marketplace:uninstall',
  MARKETPLACE_INSTALLED_LIST: 'marketplace:installed-list',
} as const;

// Synchronous boot reads (ipcRenderer.sendSync ↔ ipcMain.on + event.returnValue)
export const IPC_SYNC = {
  APP_BOOT_SETTINGS: 'app:boot-settings',
} as const;

// Push Events (webContents.send → ipcRenderer.on)
export const IPC_EVENT = {
  APP_BOOT_STATE_CHANGED: 'event:app-boot-state-changed',
  APP_FILE_FLUSH_REQUESTED: 'event:app-file-flush-requested',
  UPDATE_STATE_CHANGED: 'event:update-state-changed',
  PANE_ACTIVITY_CHANGED: 'event:pane-activity-changed',
  PANE_LIST_CHANGED: 'event:pane-list-changed',
  TERMINAL_DATA: 'event:terminal-data',
  TERMINAL_RENDERER_RESET: 'event:terminal-renderer-reset',
  TOAST: 'event:toast',
  PROGRESS: 'event:progress',
  AGENT_SESSION_UPDATED: 'event:agent-session-updated',
  AGENT_SESSION_REMOVED: 'event:agent-session-removed',
  TOPICS_UPDATED: 'event:topics-updated',
  TOPICS_REMOVED: 'event:topics-removed',
  KANBAN_CHANGED: 'event:kanban-changed',
  PERFORMANCE_METRICS: 'event:performance-metrics',
  FILE_CHANGED: 'event:file-changed',
  LSP_EVENT: 'event:lsp',
  PANE_SUMMARY_UPDATED: 'event:pane-summary-updated',
  PANE_SUMMARY_REMOVED: 'event:pane-summary-removed',
  TERMINAL_STREAM_MODE_CHANGED: 'event:terminal-stream-mode-changed',
  WINDOW_FULL_SCREEN_CHANGED: 'event:window-full-screen-changed',
} as const;
