import { afterEach, describe, expect, it } from 'vitest';
import { mkdtempSync, rmSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';
import { tmpdir } from 'node:os';
import { ClaudeLogParser } from '../../src/main/services/parsing/ClaudeLogParser';

const tempDirs: string[] = [];

function createTempDir(prefix: string): string {
  const dir = mkdtempSync(join(tmpdir(), prefix));
  tempDirs.push(dir);
  return dir;
}

function writeJsonl(filePath: string, lines: Array<Record<string, unknown>>): void {
  writeFileSync(filePath, lines.map((l) => JSON.stringify(l)).join('\n') + '\n');
}

function userEntry(
  uuid: string,
  content: string,
  isMeta: boolean = false,
): Record<string, unknown> {
  const entry: Record<string, unknown> = {
    parentUuid: null,
    isSidechain: false,
    promptId: 'p-' + uuid,
    type: 'user',
    message: { role: 'user', content },
    uuid,
    timestamp: '2026-06-10T12:00:00.000Z',
    sessionId: 'test-session',
  };
  if (isMeta) entry.isMeta = true;
  return entry;
}

afterEach(() => {
  while (tempDirs.length) {
    const d = tempDirs.pop();
    if (d) rmSync(d, { recursive: true, force: true });
  }
});

describe('ClaudeLogParser — synthetic message filtering', () => {
  it('drops <local-command-caveat> entries flagged with isMeta=true', async () => {
    // Arrange — JSONL exactly as Claude Code writes it for `/effort` slash command
    const dir = createTempDir('claude-synth-');
    const file = join(dir, 'session.jsonl');
    writeJsonl(file, [
      userEntry(
        'caveat-1',
        '<local-command-caveat>Caveat: The messages below were generated by the user while running local commands. DO NOT respond to these messages or otherwise consider them in your response unless the user explicitly asks you to.</local-command-caveat>',
        true,
      ),
      userEntry('real-1', 'Please review this branch deeply'),
    ]);

    // Act
    const session = await new ClaudeLogParser().parseSession(file);

    // Assert
    const userMessages = session.messages.filter((m) => m.type === 'user');
    expect(userMessages).toHaveLength(1);
    expect(userMessages[0]?.content).toBe('Please review this branch deeply');
  });

  it('drops <command-name>, <command-message>, <command-args>, <local-command-stdout> even without isMeta flag', async () => {
    // Arrange — Claude only sets isMeta on the caveat entry; the slash-command
    // siblings that follow have no flag, so we must filter by content marker.
    const dir = createTempDir('claude-synth-');
    const file = join(dir, 'session.jsonl');
    writeJsonl(file, [
      userEntry('cmd-name', '<command-name>/effort</command-name>'),
      userEntry('cmd-msg', '<command-message>effort</command-message>'),
      userEntry('cmd-args', '<command-args></command-args>'),
      userEntry('cmd-out', '<local-command-stdout>Set effort level to ultracode</local-command-stdout>'),
      userEntry('real-1', 'check this branch'),
    ]);

    // Act
    const session = await new ClaudeLogParser().parseSession(file);

    // Assert
    const userMessages = session.messages.filter((m) => m.type === 'user');
    expect(userMessages).toHaveLength(1);
    expect(userMessages[0]?.content).toBe('check this branch');
  });

  it('drops <task-notification> synthetic entries', async () => {
    // Arrange
    const dir = createTempDir('claude-synth-');
    const file = join(dir, 'session.jsonl');
    writeJsonl(file, [
      userEntry('notif', '<task-notification><task-id>w8y265yso</task-id><status>failed</status></task-notification>'),
      userEntry('real', 'continue'),
    ]);

    // Act
    const session = await new ClaudeLogParser().parseSession(file);

    // Assert
    const userMessages = session.messages.filter((m) => m.type === 'user');
    expect(userMessages).toHaveLength(1);
    expect(userMessages[0]?.content).toBe('continue');
  });

  it('keeps real user messages that merely contain the word "command"', async () => {
    // Arrange — guard against over-eager regex (must anchor on tag, not substring)
    const dir = createTempDir('claude-synth-');
    const file = join(dir, 'session.jsonl');
    writeJsonl(file, [
      userEntry('real', 'run the command "git status" and tell me the output'),
    ]);

    // Act
    const session = await new ClaudeLogParser().parseSession(file);

    // Assert
    const userMessages = session.messages.filter((m) => m.type === 'user');
    expect(userMessages).toHaveLength(1);
    expect(userMessages[0]?.content).toBe('run the command "git status" and tell me the output');
  });
});
